[package]
name = "bubble_sort"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"

[dev-dependencies]
criterion = "0.3.5"

[[bench]]
name = "bubble_sort_benchmark"
harness = false